artifact_location: file:///Users/dianaterraza/Desktop/corporacion_favorita/mlflow_results/694996747944737169
creation_time: 1736847837127
experiment_id: '694996747944737169'
last_update_time: 1736847837127
lifecycle_stage: active
name: Demand Forecast Experiment
